apiVersion: v2
name: my-bank-accounts
description: Sub-chart for Accounts microservice
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: java-app
    version: "1.0.0"
    repository: "file://../../library/java-app"