keycloak:
  image:
    repository: bitnamilegacy/keycloak
  auth:
    adminUser: admin
    existingSecret: my-bank-secret
    passwordSecretKey: keycloak.admin.password
  postgresql:
    image:
      repository: bitnamilegacy/postgresql
    auth:
      existingSecret: my-bank-secret
      secretKeys:
        adminPasswordKey: db.admin.password         # пароль суперпользователя БД
        userPasswordKey: keycloak.db.user.password  # пароль юзера keycloak к БД